steps:
- name: 'gcr.io/cloud-builders/docker'
  id: pull-app-image-cache
  args: ['pull', 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest']

- name: 'gcr.io/cloud-builders/docker'
  id: build-app-image
  waitFor: ['pull-app-image-cache']              # don't wait for previous steps
  args: [
    'build',
    '-f', 'k8s/images/app/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest',
    '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  id: build-nginx-image
  waitFor: ['-']              # don't wait for previous steps
  args: [
    'build',
    '-f', 'k8s/images/nginx/Dockerfile',
    '--cache-from', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest', 
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: push-app-image
  waitFor: ['build-app-image']
  args: ['push', 'gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  id: push-nginx-image
  waitFor: ['build-nginx-image']
  args: ['push', 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt-gcs-service-account
  waitFor: ['-']
  args: [
  'kms', 'decrypt',
  '--location=global', '--keyring=builder-secrets', '--key=secret-encrypter',
  '--ciphertext-file=k8s/build-secrets/$PROJECT_ID-gcs-service-account.json.enc',
  '--plaintext-file=gcs-service-account.json'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: create-new-database
  waitFor: ['-']
  args: [
  'sql', 'databases', 'create', '$COMMIT_SHA', '--instance=studio-qa'
  ]

- name: 'gcr.io/$PROJECT_ID/helm'
  id: helm-deploy-studio-instance
  waitFor: ['decrypt-gcs-service-account', 'push-app-image', 'push-nginx-image']
  dir: "k8s"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=dev-qa-cluster'
  secretEnv: ['POSTMARK_API_KEY']
  entrypoint: 'bash'
  args: [
  '-c',
  # still run helm.bash to initialze creds, but otherwise run our own deploy script
  '/builder/helm.bash && ./helm-deploy.sh $BRANCH_NAME studio-qa-content $COMMIT_SHA $$POSTMARK_API_KEY arontest $COMMIT_SHA arontest ops-central-studio-qa-sql-proxy-gcloud-sqlproxy.sqlproxy ../gcs-service-account.json'
  ]

timeout: 3600s
secrets:
- kmsKeyName: projects/ops-central/locations/global/keyRings/builder-secrets/cryptoKeys/secret-encrypter
  secretEnv:
    POSTMARK_API_KEY: CiQA7z1GH3QhvCEWNn6KS64t/c8BEQng5I4CdMC6VGNxJkWmZrwSTgB+R8mv/PSrzlDmCYSOZc4bugWA+K+lJ8nIll1BBsZZEV5M9GuOCYVn6sVWg9pCIVujwyb4EvEy1QaKmZCzAnTw9aHEXDH0sruAUHBaTA==

images:
  - 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-nginx:latest'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/learningequality-studio-app:latest'
