---
# A set of values that are meant to be used for a production setup.
# This includes:
# - an external Postgres, GCS Storage, and external Redis
# - real email sending
# - studio production settings
#
# Note that the secrets will have to be filled up by the caller
# through helm upgrade --set. See REPLACEME placeholders
# for values that need to be set.

settings: contentcuration.production_settings

productionIngress: false

studioApp:
  imageName: "REPLACEME"        
  postmarkApiKey: "REPLACEME"
  releaseCommit:
  replicas: 3
  gcs:
    enabled: true
  gDrive:
    keyJson:

sentry:
  dsnKey: ""

studioNginx:
  imageName: "REPLACEME"

postgresql:
  postgresUser: "REPLACEME"
  postgresDatabase: "REPLACEME"
  postgresPassword: "REPLACEME"
  internalDBEnabled: false
  externalCloudSQL:
    enabled: true
    proxyHostName: "REPLACEME"

minio:
  internalMinioEnabled: false
  externalGoogleCloudStorage:
    enabled: true
    # make sure gcsKeyJson has been base64-d by the time it's passed into here
    gcsKeyJson: "REPLACEME"

redis:
  internalRedisEnabled: true
