# this is meant to be mounted as a folder in the filesystem vs. env vars for studio-secrets.yaml
# hence why it's separate from studio-secrets.yaml
{{- if .Values.studioApp.gDrive.keyJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}-gdrive
  labels:
    app: {{ template "studio.name" . }}
    chart: {{ template "studio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gdrive_key.json: {{ .Values.studioApp.gDrive.keyJson }}
{{- end }}
