---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}
spec:
  replicas: {{ .Values.studioApp.replicas }}
  template:
    metadata:
      annotations:
        checksum: {{ include (print $.Template.BasePath "/studio-secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "studio.fullname" . }}
        tier: app
    spec:
      containers:
      - name: app
        image: {{ .Values.studioApp.imageName }}
        env:
        {{ include "studio.sharedEnvs" . }}
        - name: STATICFILES_DIR
          value: /app/contentworkshop_static/
        - name: SEND_USER_ACTIVATION_NOTIFICATION_EMAIL
          value: "true"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.studioApp.appPort }}
          initialDelaySeconds: 300
          periodSeconds: 5
        ports:
        - containerPort: {{ .Values.studioApp.appPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.studioNginx.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /app/contentworkshop_static/
          name: staticfiles
        - name: gcs-creds
          mountPath: /secrets/gcs
        {{ if .Values.studioApp.gDrive.keyJson }}
        - name: gdrive-creds
          mountPath: /secrets/gdrive
        {{ end }}
        resources:
          requests:
            cpu: 1000m
      - name: nginx-proxy
        image: {{ .Values.studioNginx.imageName }}
        env:
        {{ if .Values.minio.externalGoogleCloudStorage.enabled }}
        - name: AWS_S3_ENDPOINT_URL
          value: https://storage.googleapis.com
        {{ else }}
        - name: AWS_S3_ENDPOINT_URL
          value: {{ template "minio.url" . }}
        {{ end }}
        - name: AWS_BUCKET_NAME
          value: {{ .Values.bucketName }}
        ports:
        - containerPort: {{ .Values.studioNginx.port }}
        volumeMounts:
        - mountPath: /app/contentworkshop_static/
          name: staticfiles
      volumes:
        - name: gcs-creds
          secret:
            secretName: {{ template "studio.fullname" . }}-gcs
        - emptyDir: {}
          name: staticfiles
        {{ if .Values.studioApp.gDrive.keyJson }}
        - name: gdrive-creds
          secret:
            secretName: {{ template "studio.fullname" . }}-gdrive
        {{ end }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{template "studio.fullname" . }}-workers
spec:
  replicas: {{ .Values.studioWorkers.replicas }}
  template:
    metadata:
      labels:
        app: {{template "studio.fullname" . }}-workers
        tier: workers
    spec:
      volumes:
      - name: gcs-creds
        secret:
          secretName: {{ template "studio.fullname" . }}-gcs
      containers:
      - name: worker
        image: {{ .Values.studioApp.imageName }}
        command:
        - make
        - prodceleryworkers
        volumeMounts:
        - name: gcs-creds
          mountPath: /secrets/gcs
        env:
        {{ include "studio.sharedEnvs" . }}
